#ifndef WASGO_FUNCTION_TABLE
#define WASGO_FUNCTION_TABLE
#include "wasm_export.h"
#include "wasgo_state.h"
#include "wasgo_native_wrappers.h"
static NativeSymbol native_symbols[] = 
{
EXPORT_WASM_API_WITH_SIG(_wasgo_this_node,"()i"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_bool,"(*~)i"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_bool,"(*~i)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_int,"(*~)i"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_int,"(*~I)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_float,"(*~)f"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_float,"(*~f)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_string,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_string,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_vector2,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_vector2,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_rect2,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_rect2,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_vector3,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_vector3,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_transform2d,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_transform2d,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_plane,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_plane,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_quat,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_quat,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_basis,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_basis,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_aabb,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_aabb,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_transform,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_transform,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_color,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_color,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_nodepath,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_nodepath,"(*~*~)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_get_property_object,"(*~)i"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_property_object,"(*~i)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_process,"(i)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_physics_process,"(i)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_process_internal,"(i)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_physics_process_internal,"(i)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_process_input,"(i)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_process_unhandled_input,"(i)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_set_process_unhandled_key_input,"(i)"),
EXPORT_WASM_API_WITH_SIG(_wasgo_is_processing,"()"),
EXPORT_WASM_API_WITH_SIG(_wasgo_is_physics_processing,"()"),
EXPORT_WASM_API_WITH_SIG(_wasgo_is_processing_internal,"()"),
EXPORT_WASM_API_WITH_SIG(_wasgo_is_physics_processing_internal,"()"),
//EXPORT_WASM_API_WITH_SIG(_wasgo_is_processing_input,"()"),
//EXPORT_WASM_API_WITH_SIG(_wasgo_is_processing_unhandled_input,"()"),
//EXPORT_WASM_API_WITH_SIG(_wasgo_is_processing_unhandled_key_input,"()"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_accumulate, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_as_text, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_get_action_strength, "(i*~)f"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_get_device, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_is_action, "(i*~)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_is_action_pressed, "(i*~i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_is_action_released, "(i*~)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_is_action_type, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_is_echo, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_is_pressed, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_set_device, "(iI)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_shortcut_match, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_wrapper_xformed_by, "(i*~*~)i"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_InputEvent_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventAction_wrapper_get_action, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventAction_wrapper_get_strength, "(i)f"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventAction_wrapper_set_action, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventAction_wrapper_set_pressed, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventAction_wrapper_set_strength, "(if)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventAction_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventKey_wrapper_get_scancode, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventKey_wrapper_get_scancode_with_modifiers, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventKey_wrapper_get_unicode, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventKey_wrapper_set_echo, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventKey_wrapper_set_pressed, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventKey_wrapper_set_scancode, "(iI)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventKey_wrapper_set_unicode, "(iI)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventKey_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouse_wrapper_get_button_mask, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouse_wrapper_get_global_position, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouse_wrapper_get_position, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouse_wrapper_set_button_mask, "(iI)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouse_wrapper_set_global_position, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouse_wrapper_set_position, "(i*~)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouse_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseButton_wrapper_get_button_index, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseButton_wrapper_get_factor, "(i)f"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseButton_wrapper_is_doubleclick, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseButton_wrapper_set_button_index, "(iI)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseButton_wrapper_set_doubleclick, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseButton_wrapper_set_factor, "(if)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseButton_wrapper_set_pressed, "(ii)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseButton_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseMotion_wrapper_get_pressure, "(i)f"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseMotion_wrapper_get_relative, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseMotion_wrapper_get_speed, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseMotion_wrapper_get_tilt, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseMotion_wrapper_set_pressure, "(if)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseMotion_wrapper_set_relative, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseMotion_wrapper_set_speed, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseMotion_wrapper_set_tilt, "(i*~)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventMouseMotion_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_get_alt, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_get_command, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_get_control, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_get_metakey, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_get_shift, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_set_alt, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_set_command, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_set_control, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_set_metakey, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_wrapper_set_shift, "(ii)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_InputEventWithModifiers_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_add_child, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_add_child_below_node, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_add_to_group, "(i*~i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_can_process, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_duplicate, "(iI)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_find_node, "(i*~ii)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_find_parent, "(i*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_child, "(iI)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_child_count, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_children, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_custom_multiplayer, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_filename, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_groups, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_index, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_multiplayer, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_name, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_network_master, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_node, "(i*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_node_and_resource, "(i*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_node_or_null, "(i*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_owner, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_parent, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_path, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_path_to, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_pause_mode, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_physics_process_delta_time, "(i)f"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_position_in_parent, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_process_delta_time, "(i)f"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_process_priority, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_scene_instance_load_placeholder, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_tree, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_get_viewport, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_has_node, "(i*~)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_has_node_and_resource, "(i*~)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_a_parent_of, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_displayed_folded, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_greater_than, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_in_group, "(i*~)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_inside_tree, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_network_master, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_physics_processing, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_physics_processing_internal, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_processing, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_processing_input, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_processing_internal, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_processing_unhandled_input, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_is_processing_unhandled_key_input, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_move_child, "(iI)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_print_stray_nodes, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_print_tree, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_print_tree_pretty, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_propagate_call, "(i*~i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_propagate_notification, "(iI)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_queue_free, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_raise, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_remove_and_skip, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_remove_child, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_remove_from_group, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_replace_by, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_request_ready, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rpc, "(i*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rpc_config, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rpc_id, "(iI*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rpc_unreliable, "(i*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rpc_unreliable_id, "(iI*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rset, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rset_config, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rset_id, "(iI*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rset_unreliable, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_rset_unreliable_id, "(iI*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_custom_multiplayer, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_display_folded, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_filename, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_name, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_network_master, "(iIi)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_owner, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_pause_mode, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_physics_process, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_physics_process_internal, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_process, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_process_input, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_process_internal, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_process_priority, "(iI)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_process_unhandled_input, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_process_unhandled_key_input, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_set_scene_instance_load_placeholder, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Node_wrapper_update_configuration_warning, "(i)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_Node_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_duplicate, "(ii)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_get_local_scene, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_get_name, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_get_path, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_get_rid, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_is_local_to_scene, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_set_local_to_scene, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_set_name, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_set_path, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_setup_local_to_scene, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_wrapper_take_over_path, "(i*~)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_Resource_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_call_group, "(i*~*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_call_group_flags, "(iI*~*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_change_scene, "(i*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_change_scene_to, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_create_timer, "(ifi)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_current_scene, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_edited_scene_root, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_frame, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_multiplayer, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_network_connected_peers, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_network_peer, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_network_unique_id, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_node_count, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_nodes_in_group, "(i*~)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_root, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_get_rpc_sender_id, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_has_group, "(i*~)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_has_network_peer, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_is_debugging_collisions_hint, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_is_debugging_navigation_hint, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_is_input_handled, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_is_multiplayer_poll_enabled, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_is_network_server, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_is_paused, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_is_refusing_new_network_connections, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_is_using_font_oversampling, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_notify_group, "(i*~I)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_notify_group_flags, "(iI*~I)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_queue_delete, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_quit, "(iI)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_reload_current_scene, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_auto_accept_quit, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_current_scene, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_debug_collisions_hint, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_debug_navigation_hint, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_edited_scene_root, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_group, "(i*~*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_group_flags, "(iI*~*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_input_as_handled, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_multiplayer, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_multiplayer_poll_enabled, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_network_peer, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_pause, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_quit_on_go_back, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_refuse_new_network_connections, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_screen_stretch, "(i*~f)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_wrapper_set_use_font_oversampling, "(ii)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_SceneTree_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_force_update_transform, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_get_gizmo, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_get_global_transform, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_get_parent_spatial, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_get_rotation, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_get_rotation_degrees, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_get_scale, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_get_transform, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_get_translation, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_get_world, "(i)i"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_global_rotate, "(i*~f)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_global_scale, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_global_translate, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_hide, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_is_local_transform_notification_enabled, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_is_scale_disabled, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_is_set_as_toplevel, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_is_transform_notification_enabled, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_is_visible, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_is_visible_in_tree, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_look_at, "(i*~*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_look_at_from_position, "(i*~*~*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_orthonormalize, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_rotate, "(i*~f)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_rotate_object_local, "(i*~f)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_rotate_x, "(if)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_rotate_y, "(if)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_rotate_z, "(if)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_scale_object_local, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_as_toplevel, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_disable_scale, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_gizmo, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_global_transform, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_identity, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_ignore_transform_notification, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_notify_local_transform, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_notify_transform, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_rotation, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_rotation_degrees, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_scale, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_transform, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_translation, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_set_visible, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_show, "(i)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_to_global, "(i*~*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_to_local, "(i*~*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_translate, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_translate_object_local, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_wrapper_update_gizmo, "(i)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_Spatial_constructor,"()i"),
        
	EXPORT_WASM_API_WITH_SIG(_wasgo_SpatialVelocityTracker_wrapper_get_tracked_linear_velocity, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SpatialVelocityTracker_wrapper_is_tracking_physics_step, "(i)I"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SpatialVelocityTracker_wrapper_reset, "(i*~)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SpatialVelocityTracker_wrapper_set_track_physics_step, "(ii)"),
	EXPORT_WASM_API_WITH_SIG(_wasgo_SpatialVelocityTracker_wrapper_update_position, "(i*~)"),

    EXPORT_WASM_API_WITH_SIG(_wasgo_SpatialVelocityTracker_constructor,"()i"),
        
};
#endif